---

# Loosely based on geerlingguy's way to test ansible roles.
# See https://www.jeffgeerling.com/blog/2018/how-i-test-ansible-configuration-on-7-different-oses-docker.

services: docker

env:
#  - distro_name: debian9
  - distro_name: debian8
#  - distro_name: ubuntu16.04
  - distro_name: ubuntu14.04

script:

  - tests/test.sh -vvv

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
