---

# Loosely based on geerlingguy's way to test ansible roles.
# See https://www.jeffgeerling.com/blog/2018/how-i-test-ansible-configuration-on-7-different-oses-docker.

services: docker

env:
  - distro_name: debian9
  - distro_name: debian8
  - distro_name: ubuntu1804
  - distro_name: ubuntu1604
  - distro_name: ubuntu1404
  - distro_name: centos7
  - distro_name: fedora27
  - distro_name: fedora24


script:

  - tests/test.sh -vvvv

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
