---

# Loosely based on geerlingguy's way to test ansible roles.
# See https://www.jeffgeerling.com/blog/2018/how-i-test-ansible-configuration-on-7-different-oses-docker.

services: docker

env:
#  - distro: debian9
  - distro: debian8
#  - distro: ubuntu16.04
  - distro: ubuntu14.04

script:

  - tests/test.sh $distro

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
