---

- include: assertions.yml

- name: PRE | Get main domain.
  set_fact:
    nsb_c_main_domain: "{{ nsb_domains | first }}"

- name: PRE | Get secondary domain list.
  set_fact:
    nsb_c_secondary_domains: "{{ nsb_domains | difference(nsb_c_main_domain) }}"

- name: PRE | Get string with all involved domains
  set_fact:
    nsb_c_domains_string: "{{ nsb_domains | join(' ') }}"

- name: PRE | Pack HTTP IPv4 configuration
  set_fact:
    nsb_c_http_ipv4_listen_conf:
      interface: "{{ nsb_ipv4_interface }}"
      port: "{{ nsb_listen_port }}"
      ipv6: no
  when: nsb_ipv4_interface is not none and nsb_http_enabled

- name: PRE | Pack HTTPS IPv4 configuration
  set_fact:
    nsb_c_https_ipv4_listen_conf:
      interface: "{{ nsb_ipv4_interface }}"
      port: "{{ nsb_ssl_listen_port }}"
      ipv6: no
      http2: "{{ nsb_ssl_http2_protocol }}"
  when: nsb_ipv4_interface is not none and nsb_https_enabled

- name: PRE | Pack HTTP IPv6 configuration
  set_fact:
    nsb_c_http_ipv6_listen_conf:
      interface: "{{ nsb_ipv6_interface }}"
      port: "{{ nsb_listen_port }}"
      ipv6: yes
  when: nsb_ipv6_interface != none and nsb_http_enabled

- name: PRE | Pack HTTPS IPv6 configuration
  set_fact:
    nsb_c_https_ipv6_listen_conf:
      interface: "{{ nsb_ipv6_interface }}"
      port: "{{ nsb_ssl_listen_port }}"
      ipv6: yes
      http2: "{{ nsb_ssl_http2_protocol }}"
  when: nsb_ipv6_interface != none and nsb_https_enabled

# Build net configuration by concatenating variables. NOTE: Not sure why
# selecting 'sequence' values filters null values. Selected items are in fact
# dictionaries. Are Python dictionaries actually sequences?
- name: PRE | Build net interface listen configurations
  set_fact:
    nsb_c_http_net_listen_conf: "{{ ([nsb_c_http_ipv4_listen_conf]  +  [nsb_c_http_ipv6_listen_conf] + nsb_additional_http_listen_configuration)|select('sequence')|list }}"  # noqa 204
    nsb_c_https_net_listen_conf: "{{ ([nsb_c_https_ipv4_listen_conf]  +  [nsb_c_https_ipv6_listen_conf] + nsb_additional_https_listen_configuration)|select('sequence')|list }}"  # noqa 204

- name: SITE | Deploy server configuration file
  template:
    src: "nginx_server_conf.j2"
    dest: "{{ nsb_nginx_conf_dir }}/{{ nsb_nginx_sites_available_path }}/{{ nsb_c_main_domain }}.conf"
    owner: "{{ nsb_conf_file_owner }}"
    group: "{{ nsb_conf_file_group }}"
    mode: 0640
  when: nsb_distro_allows_disabling_sites or (nsb_server_block_enabled and not nsb_distro_allows_disabling_sites)
  notify: NSB reload nginx

- name: SITE | Enable/disable server block configuration
  file:
    src: "{{ nsb_nginx_conf_dir }}/{{ nsb_nginx_sites_available_path }}/{{ nsb_c_main_domain }}.conf"
    dest: "{{ nsb_nginx_conf_dir }}/{{ nsb_nginx_sites_enabled_path }}/{{ nsb_c_main_domain }}.conf"
    state: "{{ nsb_server_block_enabled |ternary('link', 'absent') }}"
  when: nsb_distro_allows_disabling_sites
  notify: NSB reload nginx
